### ISSUE TITLE
vim, plugin lexima <CR> do not work

### ISSUE THREAD

**Issue by shimo164** [shimo164/issues#3]
**When:**
input this...
**(\<CR>**

**Result:**

(
\<Cursor>)

**Expect:**

(
\<Tab><Cursor>
)

**Env:**
Ubuntu16.04
Vim 8.1

(in my Windows7, vim8.1, this do not happen)

--
same problem as:
https://github.com/cohama/lexima.vim/issues/81
in comment above issue url, lemima is coflicting...need to check.

**Comment by shimo164** [comment]
Plugin caw conflicts. 
Removing caw will works.
Need to find setting to use both caw and lexima.

---
Edit:
It appears caw does not conflict. Sometimes lexima does not work. Still surveying...

**Comment by Glavnokoman** [comment]
Neovim 0.5.0, Linux. Same behaviour.
```
:verbose imap <cr>
i  <CR>        * pumvisible() ? "\<C-Y>" : lexima#expand('<CR>', 'i')                                                                         Last set from ~/.local/share/nvim/plugged/lexima.vim/autoload/lexima/insmode.vim line 85 
```
having {|} and calling manually `:call lexima#expand('<CR>', 'i') ` has no effect.

**Comment by shimo164** [comment]
Close. I won't use vim at this time.
